# Generated by Django 5.1.7 on 2025-03-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("affiliates", "0002_affiliatecourse_unique_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="affiliatecourse",
            name="referral_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
