# Generated by Django 5.1.7 on 2025-03-15 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("affiliates", "0006_auto_20250315_1352"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="affiliate_seller",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="affiliate_sales",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
