# Generated by Django 5.1.7 on 2025-03-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("affiliates", "0007_alter_sale_affiliate_seller"),
    ]

    operations = [
        migrations.AddField(
            model_name="affiliate",
            name="available_vendor_earnings",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="affiliate",
            name="overall_vendor_earnings",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="affiliate",
            name="total_withdrawals",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
