# Generated by Django 5.1.7 on 2025-03-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="courserequest",
            name="affiliate_commission",
            field=models.DecimalField(decimal_places=2, default=0.4, max_digits=4),
        ),
        migrations.AddField(
            model_name="courserequest",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
