# Generated by Django 5.1.7 on 2025-03-22 14:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_remove_lesson_video_url_lesson_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userregisteredcourse",
            unique_together={("user", "course")},
        ),
    ]
