# Generated by Django 5.1.1 on 2025-03-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_withdrawalrequest_account_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="account_name",
            field=models.CharField(default="Unknown", max_length=255),
        ),
    ]
