# Generated by Django 5.1.7 on 2025-03-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0004_payment_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="withdrawalrequest",
            name="withdrawal_type",
            field=models.CharField(
                choices=[
                    ("affiliate", "Affiliate Earnings"),
                    ("vendor", "Vendor Earnings"),
                ],
                default="affiliate",
                max_length=10,
            ),
        ),
    ]
